// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6911768874964897874),
    name: 'ChoiceCatalogItemEntity',
    lastPropertyId: const obx_int.IdUid(4, 7558930253291543801),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5021697592155729798),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 521812086996054153),
        name: 'categoryKey',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 2586203854262691341),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4229299553868808104),
        name: 'valueAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7558930253291543801),
        name: 'noteFr',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7431668201049795761),
    name: 'DossierSubmissionEntity',
    lastPropertyId: const obx_int.IdUid(10, 4171148562112665394),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3712843670694365510),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9209134794721521837),
        name: 'wilaya',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 2983722617607919945),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5919673865889978343),
        name: 'applicantName',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 4456994138045653281),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7503585546776980494),
        name: 'companyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5284894193070665610),
        name: 'installationAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3632987122716650437),
        name: 'installerCompany',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6578146487429737219),
        name: 'totalQty',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3963102727586332301),
        name: 'strikeExternalMarket',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5547405669485174389),
        name: 'fieldsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4171148562112665394),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(4, 8231009174002444483),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7431668201049795761),
    lastIndexId: const obx_int.IdUid(4, 8231009174002444483),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChoiceCatalogItemEntity: obx_int.EntityDefinition<ChoiceCatalogItemEntity>(
      model: _entities[0],
      toOneRelations: (ChoiceCatalogItemEntity object) => [],
      toManyRelations: (ChoiceCatalogItemEntity object) => {},
      getId: (ChoiceCatalogItemEntity object) => object.id,
      setId: (ChoiceCatalogItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChoiceCatalogItemEntity object, fb.Builder fbb) {
        final categoryKeyOffset = fbb.writeString(object.categoryKey);
        final valueArOffset = fbb.writeString(object.valueAr);
        final noteFrOffset = fbb.writeString(object.noteFr);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categoryKeyOffset);
        fbb.addOffset(2, valueArOffset);
        fbb.addOffset(3, noteFrOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final noteFrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = ChoiceCatalogItemEntity(
          id: idParam,
          categoryKey: categoryKeyParam,
          valueAr: valueArParam,
          noteFr: noteFrParam,
        );

        return object;
      },
    ),
    DossierSubmissionEntity: obx_int.EntityDefinition<DossierSubmissionEntity>(
      model: _entities[1],
      toOneRelations: (DossierSubmissionEntity object) => [],
      toManyRelations: (DossierSubmissionEntity object) => {},
      getId: (DossierSubmissionEntity object) => object.id,
      setId: (DossierSubmissionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DossierSubmissionEntity object, fb.Builder fbb) {
        final wilayaOffset = fbb.writeString(object.wilaya);
        final applicantNameOffset = fbb.writeString(object.applicantName);
        final companyNameOffset = fbb.writeString(object.companyName);
        final installationAddressOffset = fbb.writeString(
          object.installationAddress,
        );
        final installerCompanyOffset = fbb.writeString(object.installerCompany);
        final totalQtyOffset = fbb.writeString(object.totalQty);
        final fieldsJsonOffset = fbb.writeString(object.fieldsJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, wilayaOffset);
        fbb.addOffset(2, applicantNameOffset);
        fbb.addOffset(3, companyNameOffset);
        fbb.addOffset(4, installationAddressOffset);
        fbb.addOffset(5, installerCompanyOffset);
        fbb.addOffset(6, totalQtyOffset);
        fbb.addBool(7, object.strikeExternalMarket);
        fbb.addOffset(8, fieldsJsonOffset);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final wilayaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final applicantNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final companyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final installationAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final installerCompanyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final totalQtyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final strikeExternalMarketParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final fieldsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = DossierSubmissionEntity(
          id: idParam,
          wilaya: wilayaParam,
          applicantName: applicantNameParam,
          companyName: companyNameParam,
          installationAddress: installationAddressParam,
          installerCompany: installerCompanyParam,
          totalQty: totalQtyParam,
          strikeExternalMarket: strikeExternalMarketParam,
          fieldsJson: fieldsJsonParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChoiceCatalogItemEntity] entity fields to define ObjectBox queries.
class ChoiceCatalogItemEntity_ {
  /// See [ChoiceCatalogItemEntity.id].
  static final id = obx.QueryIntegerProperty<ChoiceCatalogItemEntity>(
    _entities[0].properties[0],
  );

  /// See [ChoiceCatalogItemEntity.categoryKey].
  static final categoryKey = obx.QueryStringProperty<ChoiceCatalogItemEntity>(
    _entities[0].properties[1],
  );

  /// See [ChoiceCatalogItemEntity.valueAr].
  static final valueAr = obx.QueryStringProperty<ChoiceCatalogItemEntity>(
    _entities[0].properties[2],
  );

  /// See [ChoiceCatalogItemEntity.noteFr].
  static final noteFr = obx.QueryStringProperty<ChoiceCatalogItemEntity>(
    _entities[0].properties[3],
  );
}

/// [DossierSubmissionEntity] entity fields to define ObjectBox queries.
class DossierSubmissionEntity_ {
  /// See [DossierSubmissionEntity.id].
  static final id = obx.QueryIntegerProperty<DossierSubmissionEntity>(
    _entities[1].properties[0],
  );

  /// See [DossierSubmissionEntity.wilaya].
  static final wilaya = obx.QueryStringProperty<DossierSubmissionEntity>(
    _entities[1].properties[1],
  );

  /// See [DossierSubmissionEntity.applicantName].
  static final applicantName = obx.QueryStringProperty<DossierSubmissionEntity>(
    _entities[1].properties[2],
  );

  /// See [DossierSubmissionEntity.companyName].
  static final companyName = obx.QueryStringProperty<DossierSubmissionEntity>(
    _entities[1].properties[3],
  );

  /// See [DossierSubmissionEntity.installationAddress].
  static final installationAddress =
      obx.QueryStringProperty<DossierSubmissionEntity>(
        _entities[1].properties[4],
      );

  /// See [DossierSubmissionEntity.installerCompany].
  static final installerCompany =
      obx.QueryStringProperty<DossierSubmissionEntity>(
        _entities[1].properties[5],
      );

  /// See [DossierSubmissionEntity.totalQty].
  static final totalQty = obx.QueryStringProperty<DossierSubmissionEntity>(
    _entities[1].properties[6],
  );

  /// See [DossierSubmissionEntity.strikeExternalMarket].
  static final strikeExternalMarket =
      obx.QueryBooleanProperty<DossierSubmissionEntity>(
        _entities[1].properties[7],
      );

  /// See [DossierSubmissionEntity.fieldsJson].
  static final fieldsJson = obx.QueryStringProperty<DossierSubmissionEntity>(
    _entities[1].properties[8],
  );

  /// See [DossierSubmissionEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<DossierSubmissionEntity>(
    _entities[1].properties[9],
  );
}
